train_model:
  random_state: 42
  test_size: 0.2
  param_grid:
    n_estimators: [2, 5]
    max_features: ["auto", "sqrt"]
    max_depth: [4, 5, 10]
    criterion: ["gini", "entropy"]
segregate_data:
  random_state: 42
  test_size: 0.2
